[project]
name = "ml-orchestrator"
version = "0.1.0"
description = "Scalable GCP Vertex AI pipeline orchestration wrapper using Kubeflow Pipelines"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
]
dependencies = [
    "google-cloud-aiplatform>=1.35.0",
    "kfp>=2.0.1",
    "google-cloud-secret-manager>=2.16.0",
    "gitpython>=3.1.40",
    "pyyaml>=6.0.1",
    "python-dotenv>=1.0.0",
    "loguru>=0.7.0",
]

[project.optional-dependencies]
build = ["build>=1.0.0", "twine>=4.0.0"]
dev = [
    "pytest>=7.4.0",
    "black>=24.3.0",
    "isort>=5.12.0",
    "pre-commit>=3.5.0",
    "docformatter>=1.7.7",
    "Jinja2>=3.1.0",
    "google-cloud-storage>=2.1.0",
]
test = [
    "mypy>=1.11.0",
    "pylint>=3.0.0",
    "ruff>=0.6.0",
    "pytest>=7.4.0",
    "pytest-cov>=5.0.0",
    "pytest-mock>=3.0.0",
]

[project.urls]
"Homepage" = "https://github.com/your-username/ml-orchestrator"
"Repository" = "https://github.com/your-username/ml-orchestrator"
"Issues" = "https://github.com/your-username/ml-orchestrator/issues"

[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/ml_orchestrator/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/ml_orchestrator"]



[tool.mypy]
python_version = "3.11"
strict = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
strict_equality = true
extra_checks = true
check_untyped_defs = true
disallow_subclassing_any = true
disallow_untyped_decorators = true
disallow_any_generics = true
no_implicit_reexport = true
warn_return_any = true
exclude = ["google.cloud.storage"] # Exclude google.cloud.storage from mypy checks
[[tool.mypy.overrides]]
module = ["ml_orchestrator.*", "loguru", "kfp.*", "google.*", "jinja2", "google.cloud.storage"]
ignore_missing_imports = true

[tool.pylint.messages_control]
disable = [
    "import-error",
    "logging-fstring-interpolation",
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "W0107", # Disable "unnecessary pass statement" for abstract methods
    "W1404", # Disable "implicit string concatenation"
]

[tool.pylint]
max-line-length = 120 # Match ruff's line length
max-attributes = 10 # Allow up to 10 instance attributes

[tool.ruff]
line-length = 120
exclude = ["notebooks"]

[tool.ruff.lint]
select = ["E", "D", "F", "UP", "SIM", "I", "W"]
ignore = [
    "D100", "D101", "D102", "D103", "D104", "D106",
    "D401",
    "D205", # Disable "1 blank line required between summary line and description"
]
[tool.ruff.lint.isort]
known-first-party = ["ml_orchestrator"]
combine-as-imports = false
force-single-line = false
single-line-exclusions = ["google.cloud"]

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
python_files = ["test_*.py"]
testpaths = ["tests"]
addopts = "--cov=ml_orchestrator --cov-report=xml"

[[tool.uv.index]]
name = "github"
url = "https://pkg.github.com/JENO87/ml-orchestrator/pypi"
publish-url = "https://pkg.github.com/JENO87/ml-orchestrator/_registry/pypi/"
