from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Optional


# --- Abstract Contract for Overall Pipeline Settings ---
class PipelineSettings(ABC):
    """An abstract contract for overall pipeline settings.

    Concrete implementations must provide values for the abstract properties.
    This class also provides default values for optional PipelineJob parameters,
    which can be overridden by concrete implementations.
    """

    @property
    @abstractmethod
    def pipeline_display_name(self) -> str:
        """The user-facing name of the pipeline in Vertex AI.

        This is a human-readable name for the pipeline run, visible in the Vertex AI console.
        It helps in identifying and tracking different runs.
        """
        pass

    @property
    @abstractmethod
    def pipeline_description(self) -> str:
        """A brief description of the pipeline.

        This description provides context about the pipeline's purpose or functionality.
        """
        pass

    @property
    @abstractmethod
    def pipeline_root(self) -> str:
        """GCS path for pipeline artifacts (e.g., 'gs://my-bucket/pipelines').

        This is the Google Cloud Storage (GCS) URI where all output artifacts,
        intermediate results, and logs generated by your pipeline will be stored.
        The service account running the pipeline must have write permissions to this bucket.
        """
        pass

    @property
    @abstractmethod
    def experiment_name(self) -> str:
        """The name of the Vertex AI experiment to group runs under.

        Experiments help organize and compare different pipeline runs, especially
        during model development and iteration.
        """
        pass

    # Optional PipelineJob parameters with default property implementations
    @property
    def enable_caching(self) -> bool:
        """Whether to enable caching for pipeline steps. Defaults to True.

        If True, Vertex AI will attempt to reuse results from previous pipeline runs
        for identical steps (same inputs, same code), saving time and resources.
        Set to False during development to ensure every step re-executes.
        """
        return True  # Default to True for cost savings and faster reruns

    @property
    def parameter_values(self) -> Optional[dict[str, Any]]:
        """Runtime parameters for the KFP pipeline. Defaults to None.

        A dictionary of key-value pairs representing runtime parameters for your pipeline.
        These allow you to change pipeline behavior without recompiling the YAML.
        For example, `{"learning_rate": 0.01}`.
        """
        return None  # Runtime parameters for the KFP pipeline

    @property
    def input_artifacts(self) -> Optional[dict[str, str]]:
        """Input artifacts for the pipeline. Defaults to None.

        A dictionary mapping artifact names (as defined in your pipeline) to their
        corresponding GCS URIs. This allows you to inject existing artifacts
        (e.g., a pre-trained model, a dataset) into your pipeline run.
        """
        return None

    @property
    def encryption_spec_key_name(self) -> Optional[str]:
        """Cloud KMS key name for encrypting pipeline artifacts (CMEK). Defaults to None.

        Specifies a customer-managed encryption key (CMEK) to use for encrypting
        the pipeline's artifacts and metadata. Relevant for organizations with
        strict data security and compliance requirements.
        Example: `projects/PROJECT_ID/locations/LOCATION/keyRings/KEY_RING_NAME/cryptoKeys/KEY_NAME`.
        """
        return None

    @property
    def labels(self) -> dict[str, str]:
        """Additional labels for the PipelineJob. Defaults to an empty dictionary.

        Key-value pairs that you can attach to your pipeline job for organizational
        purposes. Useful for filtering, cost allocation, and automation.
        Example: `{"team": "data-science", "project_phase": "poc"}`.
        """
        return {}  # Additional labels for the PipelineJob

    @property
    def failure_policy(self) -> Optional[str]:
        """Defines behavior on task failure (e.g., 'fast_fail' or 'continue'). Defaults to None.

        If 'fast_fail', the pipeline stops immediately upon the first task failure.
        If 'continue', the pipeline attempts to continue running subsequent tasks
        even if some upstream tasks have failed, as long as their dependencies are met.
        """
        return None  # e.g., "fast_fail" or "continue"


# --- Base Class for Individual Task (Component) Settings ---
@dataclass(frozen=True)
class TaskSettings:
    """A base dataclass for standard pipeline task settings."""

    display_name: str
    cpu_limit: str = "1"
    memory_limit: str = "4G"
    enable_caching: bool = True
