import os
import subprocess
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional, cast

import tomllib


# --- Abstract Contract for Overall Pipeline Settings ---
class PipelineSettings(ABC):
    """An abstract contract for overall pipeline settings.

    Concrete implementations must provide values for the abstract properties.
    This class also provides default values for optional PipelineJob parameters,
    which can be overridden by concrete implementations.

    All concrete pipeline settings must inherit from this class.
    Centralizes:
    - Registry
    - GCS paths
    - Experiment tracking
    - Runtime behavior
    """

    @property
    @abstractmethod
    def pipeline_display_name(self) -> str:
        """The user-facing name of the pipeline in Vertex AI.

        This is a human-readable name for the pipeline run, visible in the Vertex AI console.
        It helps in identifying and tracking different runs.
        """
        pass

    @property
    @abstractmethod
    def pipeline_description(self) -> str:
        """A brief description of the pipeline.

        This description provides context about the pipeline's purpose or functionality.
        """
        pass

    @property
    @abstractmethod
    def pipeline_root(self) -> str:
        """GCS path for pipeline artifacts (e.g., 'gs://my-bucket/pipelines').

        This is the Google Cloud Storage (GCS) URI where all output artifacts,
        intermediate results, and logs generated by your pipeline will be stored.
        The service account running the pipeline must have write permissions to this bucket.
        """
        pass

    @property
    @abstractmethod
    def experiment_name(self) -> str:
        """The name of the Vertex AI experiment to group runs under.

        Experiments help organize and compare different pipeline runs, especially
        during model development and iteration.
        """
        pass

    # Optional PipelineJob parameters with default property implementations
    @property
    def enable_caching(self) -> bool:
        """Whether to enable caching for pipeline steps. Defaults to True.

        If True, Vertex AI will attempt to reuse results from previous pipeline runs
        for identical steps (same inputs, same code), saving time and resources.
        Set to False during development to ensure every step re-executes.
        """
        return True  # Default to True for cost savings and faster reruns

    @property
    def parameter_values(self) -> Optional[dict[str, Any]]:
        """Runtime parameters for the KFP pipeline. Defaults to None.

        A dictionary of key-value pairs representing runtime parameters for your pipeline.
        These allow you to change pipeline behavior without recompiling the YAML.
        For example, `{"learning_rate": 0.01}`.
        """
        return None  # Runtime parameters for the KFP pipeline

    @property
    def input_artifacts(self) -> Optional[dict[str, str]]:
        """Input artifacts for the pipeline. Defaults to None.

        A dictionary mapping artifact names (as defined in your pipeline) to their
        corresponding GCS URIs. This allows you to inject existing artifacts
        (e.g., a pre-trained model, a dataset) into your pipeline run.
        """
        return None

    @property
    def encryption_spec_key_name(self) -> Optional[str]:
        """Cloud KMS key name for encrypting pipeline artifacts (CMEK). Defaults to None.

        Specifies a customer-managed encryption key (CMEK) to use for encrypting
        the pipeline's artifacts and metadata. Relevant for organizations with
        strict data security and compliance requirements.
        Example: `projects/PROJECT_ID/locations/LOCATION/keyRings/KEY_RING_NAME/cryptoKeys/KEY_NAME`.
        """
        return None

    @property
    def labels(self) -> dict[str, str]:
        """Additional labels for the PipelineJob. Defaults to an empty dictionary.

        Key-value pairs that you can attach to your pipeline job for organizational
        purposes. Useful for filtering, cost allocation, and automation.
        Example: `{"team": "data-science", "project_phase": "poc"}`.
        """
        return {}  # Additional labels for the PipelineJob

    @property
    def failure_policy(self) -> Optional[str]:
        """Defines behavior on task failure (e.g., 'fast_fail' or 'continue'). Defaults to None.

        If 'fast_fail', the pipeline stops immediately upon the first task failure.
        If 'continue', the pipeline attempts to continue running subsequent tasks
        even if some upstream tasks have failed, as long as their dependencies are met.
        """
        return None  # e.g., "fast_fail" or "continue"


# --- Base Class for Individual Task (Component) Settings ---
@dataclass(frozen=True)
class TaskSettings:
    """A base dataclass for standard pipeline task settings."""

    display_name: str
    cpu_limit: str = "1"
    memory_limit: str = "4G"
    enable_caching: bool = True


@dataclass(frozen=True)
class BaseVarTemplateComponent(ABC):
    """
    Defines the project-wide registry and the common source for component code.
    In a wrapper project, you will create a concrete implementation of this,
    setting the registry and ONE of either the repo URL or the package spec.
    """

    registry: str

    # --- Choose ONE source mode for your project ---
    # For projects where scripts are pulled from a git repo
    source_repo_url: Optional[str]  # e.g., "https://raw.githubusercontent.com/my-org/my-repo/main"

    # For projects where code is installed from a Python package
    source_package_spec: Optional[str]  # e.g., "my-package @ git+https://github.com/my-org/my-package.git@main"


@dataclass(frozen=True)
class VarTemplateComponent(BaseVarTemplateComponent, ABC):
    """Configuration for a single, buildable component."""

    component_name: str
    base_image: str
    run_command: list[str]

    # The path to the script, relative to the repo source. Only used in repo mode.
    script_path: Optional[str] = None

    # Optional arguments to append to the run command
    args: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        """Validate configuration and load dependencies."""
        # 1. Validate the component source configuration
        is_repo_mode = self.source_repo_url is not None
        is_package_mode = self.source_package_spec is not None

        if not is_repo_mode ^ is_package_mode:
            raise ValueError(
                f"The Base Class for '{self.component_name}' must define either 'source_repo_url' "
                f"or 'source_package_spec', but not both."
            )

        if is_repo_mode and not self.script_path:
            raise ValueError(
                f"Component '{self.component_name}' is using a repo source but is missing the 'script_path' attribute."
            )

        # 2. Load dependencies from pyproject.toml
        component_deps = self._get_component_deps()
        object.__setattr__(self, "packages_to_install", component_deps)

    @property
    def full_script_url(self) -> str:
        """Constructs the full raw GitHub URL for the script."""
        if not self.source_repo_url or not self.script_path:
            raise AttributeError("full_script_url is only available for repo-sourced components.")
        # Use rstrip to ensure there's exactly one slash
        return f"{self.source_repo_url.rstrip('/')}/{self.script_path.lstrip('/')}"

    @property
    def target_path(self) -> str:
        """The path where the script will be placed inside the container."""
        if not self.script_path:
            raise AttributeError("target_path is only available for script-based components.")
        return f"/scripts/{Path(self.script_path).name}"

    def _get_component_deps(self) -> list[str]:
        """Load optional deps from pyproject.toml."""
        path = Path(__file__).resolve().parents[3] / "pyproject.toml"
        with open(path, "rb") as f:
            data: dict[str, Any] = tomllib.load(f)  # ← fixed dict type
        optional = data.get("project", {}).get("optional-dependencies", {})
        deps = optional.get(self.component_name.lower(), [])
        return cast(list[str], deps)

    def image_tag(self) -> str:
        project = self._get_project_name()
        version = self._get_version()
        env = self._get_env()
        name = f"{project}-{self.component_name}"
        return f"{self.registry}/{name}-{env}:{version}"

    def _get_project_name(self) -> str:
        path = Path(__file__).resolve().parents[3] / "pyproject.toml"
        with open(path, "rb") as f:
            data = tomllib.load(f)
        return cast(str, data["project"]["name"])

    def _get_version(self) -> str:
        """Get version from hatch."""
        try:
            result = subprocess.check_output(["hatch", "version"], text=True)
            return result.strip()
        except (subprocess.CalledProcessError, FileNotFoundError):
            return "0.1.0"

    def _get_env(self) -> str:
        branch = os.getenv("BRANCH_NAME", "development")
        return branch.split("/")[-1].lower()


@dataclass(frozen=True)
class SubmitSettings:
    """Settings for a pipeline submission."""

    experiment_name: str
    only_validate: bool = False
    wait_for_completion: bool = False
    wipe_repository_path: bool = False
    branch: Optional[dict[str, str]] = None
