name: CI Pipeline


on:
  push:
    branches: [ "main", "development", "quality" ]
  pull_request:
    branches: [ "main", "development", "quality" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'development'

# Define reusable steps with YAML anchors
defaults:
  run:
    shell: bash

jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - &checkout
        uses: actions/checkout@v4
      - &install-uv
        name: Install UV
        run: make install-uv
      - &editable-install
        name: Editable install
        run: make editable-install
      - name: Run lint checks
        run: make lint-check

  check-formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *install-uv
      - *editable-install
      - name: Check formatting
        run: make format-check

  run-type-checking:
    name: Run Type Checking
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *install-uv
      - *editable-install
      - name: Run type checking
        run: make type-check

  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *install-uv
      - *editable-install
      - name: Run unit tests
        run: make test

  generate-coverage-report:
    name: Generate Coverage Report
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *install-uv
      - *editable-install
      - name: Generate coverage report
        run: make test
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            coverage.xml
            report.xml

  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [ run-linters, check-formatting, run-type-checking, run-unit-tests ]
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && (github.ref_name == 'quality' || github.ref_name == 'main'))
    steps:
      - *checkout
      - *install-uv
      - *editable-install
      - name: Extract version
        id: get-version
        run: |
          VERSION=$(hatch version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Build package
        run: make build-package
      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist/*

  push-package:
    name: Push Package to GCP Artifact Registry
    runs-on: ubuntu-latest
    needs: [ build-package ]
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref_name, 'v'))
    steps:
      - *checkout
      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: package
          path: dist/
      - name: Load environment variables
        run: |
          echo "REGION=${{ secrets.REGION }}" >> $GITHUB_ENV
          echo "PROJECT=${{ secrets.PROJECT }}" >> $GITHUB_ENV
          echo "REPOSITORY=${{ secrets.REPOSITORY }}" >> $GITHUB_ENV
      - name: Publish package to GCP Artifact Registry
        run: |
          python -m twine upload --repository-url https://${{ env.REGION }}-python.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY}}/ dist/* \
            -u _json_key_base64 \
            -p ${{ secrets.GCP_SERVICE_ACCOUNT_BASE64 }} \
            --verbose
        env:
          TWINE_REPOSITORY_URL: https://${{ env.REGION }}-python.pkg.dev/${{ env.PROJECT }}/${{ env.REPOSITORY}}/

  export-requirements:
    name: Export Requirements
    runs-on: ubuntu-latest
    needs: [build-package]
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && (github.ref_name == 'quality' || github.ref_name == 'main'))
    steps:
      - *checkout
      - *install-uv
      - *editable-install
      - name: Export requirements
        run: make export
      - name: Upload requirements
        uses: actions/upload-artifact@v4
        with:
          name: requirements
          path: requirements.txt
